### PR TITLE
ci: Use newest patch on tests and exit non-zero on fail

### PR DESCRIPTION
**Pull request by mamg22**
As suggested in https://github.com/nsxiv/nsxiv-extra/commit/82645084574125b1c65af7eda31fa9f91ce411a4

This uses the author commit time for sorting (`%at` in the log format).

### CODE REVIEW

**Comment by mamg22** [comment]
It seems that something broke when running in the actions environment? I'll give it a check tomorrow.

**Comment by N-R-K** [comment]
> It seems that something broke when running in the actions environment? I'll give it a check tomorrow.

That seems to be due to the CWD being at `nsxiv` rather than `nsxiv-extra`. The ci fails as expected now, but it seems to be picking up some stale patches like `dmenu-mode-v27.1`

**Comment by N-R-K** [comment]
Weird, it still picked up stale patches. Running the script on my system locally works fine though. https://github.com/nsxiv/nsxiv-extra/runs/6452882430?check_suite_focus=true#step:4:8

**Comment by XPhyro** [comment]
Closing per the migration to Codeberg.

**Pull request closed without merging**
